//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkRemind.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WorkRemind.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 下班啦！下班啦！下班啦！下班啦！下班啦！下班啦！下班啦！.
        /// </summary>
        internal static string BalloonTipText {
            get {
                return ResourceManager.GetString("BalloonTipText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 提醒.
        /// </summary>
        internal static string BalloonTipTitle {
            get {
                return ResourceManager.GetString("BalloonTipTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 开始.
        /// </summary>
        internal static string BtnstartBegin {
            get {
                return ResourceManager.GetString("BtnstartBegin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 最小化.
        /// </summary>
        internal static string BtnstartMini {
            get {
                return ResourceManager.GetString("BtnstartMini", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon ico {
            get {
                object obj = ResourceManager.GetObject("ico", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 请注意！你现在可以下班了！.
        /// </summary>
        internal static string MessageBoxShow {
            get {
                return ResourceManager.GetString("MessageBoxShow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 你已经可以下班啦！.
        /// </summary>
        internal static string MessageBoxShowAlreadyOff {
            get {
                return ResourceManager.GetString("MessageBoxShowAlreadyOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 下班提醒服务正在运行....
        /// </summary>
        internal static string NotifyiconText {
            get {
                return ResourceManager.GetString("NotifyiconText", resourceCulture);
            }
        }
    }
}
